Repository AY2324S1-CS2103T-F08-0/tp, pull requests merged in 2023-10, with the labels that each got.

#26 Update User Guide
  docs/AboutUs.md
  docs/UserGuide.md
Labels: type.UG

#35 Update DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.DG

#47 Update UserGuide
  docs/UserGuide.md
Labels: type.UG

#55 Attempt to fix workflow run failure
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/frrrrry.md
Labels: bug

#63 Update DG
  docs/DeveloperGuide.md
  docs/team/frrrrry.md
Labels: type.DG

#66 Update DeveloperGuide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/team/xxiaoweii.md
Labels: type.DG

#65 Update DG
  docs/DeveloperGuide.md
Labels: type.DG

#83 Add command
  src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
Labels: enhancement

#95 Enhance fav feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindRoleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement

#121 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/team/frrrrry.md
Labels: type.DG

#122 Update PersonBuilder
  src/main/java/seedu/address/model/person/Tutorial.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug, testing

#125 Add testcases
  build.gradle
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug, testing

#126 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.DG

#129 Add Testcases
  build.gradle
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Contact.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ContactTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: testing

#130 Add Role Tag
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#133 Add Person testcases
  src/test/java/seedu/address/logic/commands/FindRoleCommandTest.java
  src/test/java/seedu/address/model/person/CourseContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TutorialContainsKeywordsPredicateTest.java
Labels: testing

#132 Update Role Tag
  src/main/java/seedu/address/ui/PersonCard.java
Labels: enhancement

#136 Add Parser testcases
  src/main/java/seedu/address/logic/parser/FindCourseCommandParser.java
  src/main/java/seedu/address/logic/parser/FindRoleCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTutorialCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCourseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTutorialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnfavouriteCommandParserTest.java
Labels: testing

#144 Add testcases for SampleDataUtil
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: testing

#145 Update testcases 1
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug, documentation
