Repository AY2324S1-CS2103T-F08-0/tp, pull requests merged in 2023-11, with the labels that each got.

#147 Add more testcases
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/CourseTest.java
Labels: testing

#152 Implement FavList
  src/main/java/seedu/address/logic/commands/FavListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/FavListCommandTest.java
Labels: enhancement

#153 Update UG
  docs/UserGuide.md
  docs/images/HelpWindow.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.UG

#165 Add edit feature in UG
  docs/UserGuide.md
Labels: type.UG

#218 Update format of the UG
  docs/UserGuide.md
Labels: type.UG

#238 Fix bugs related to Add Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug

#241 Update DG
  docs/DeveloperGuide.md
Labels: type.DG

#244 Add Command UG
  docs/UserGuide.md
Labels: bug.UG

#258 Update UG and fry's ppp
  docs/UserGuide.md
  docs/team/frrrrry.md
Labels: type.UG

#259 Revert some changes in PR #238
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Course.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug.notAllowedToFix

#248 Update xxiaoweii's PPP and DG
  docs/DeveloperGuide.md
  docs/team/xxiaoweii.md
Labels: documentation, type.DG

#260 Update UG with the updated add command
  docs/UserGuide.md
Labels: bug.UG

#274 Fix bug related to tutorial
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: bug.UG, bug.mustFix

#283 Fix bugs in UG and Add Command usage message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug.UG

#284 Fix ug bug
  docs/UserGuide.md
Labels: bug.UG

#285 Fix ug bug
  docs/UserGuide.md
Labels: bug.UG
